# ───────────────────────────────────────────
# Site settings
# ───────────────────────────────────────────
title: "Neva Crounse"
description: "Heraklion, Greece
 nevacrounse14@gmail.com"
author: "Neva Crounse"
email:

# With a custom domain you serve from the root,
# so baseurl stays empty and url is your domain.
baseurl: ""                    # e.g. "" for https://neva.wtf/
url: "https://neva.wtf"        # full URL including protocol

# ───────────────────────────────────────────
# Collection settings
# ───────────────────────────────────────────
collections:
  photos:
    output: true               # makes each photo page renderable if needed

# ───────────────────────────────────────────
# Social links (add handles/URLs when ready)
# ───────────────────────────────────────────
500px_url:
facebook_url:
github_url:
gitlab_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# ───────────────────────────────────────────
# Build settings
# ───────────────────────────────────────────
markdown: kramdown
kramdown:
  input: GFM                   # GitHub-flavoured Markdown

# Optional: keep these files out of the production build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
